### ISSUE TITLE
Support disabling certain machine checks to support TalOS and friends

### ISSUE THREAD

**Issue by ekarlso** [k8s-proxmox/cluster-api-provider-proxmox#183]
/kind feature

**Describe the solution you'd like**

I would like to be able to disable CloudInit and or QEMU checks as a part of the machine provisioning process so that distros that doesn't support these tools will work with capmox

**Anything else you would like to add:**
-

**Environment:**
Proxmox: 8.x 
capmox: master / latest
Talos: 1.8.x
K8s: 1.30.3

**Comment by sp-yduck** [comment]
Could you share any logs ?

**Comment by xeor** [comment]
Is there any plans here? I would really like to use this with Talos. Any workarounds except using ionos-cloud/cluster-api-provider-proxmox?

**Comment by xeor** [comment]
Based on https://a-cup-of.coffee/blog/talos-capi-proxmox/ (which uses ionos provider), I think what is missing is these

```
  checks:
    skipCloudInitStatus: true
    skipQemuGuestAgent: true
  metadataSettings:
    providerIDInjection: true
```
